<!DOCTYPE html>
<html lang="${lang}">

	<head>
		<#assign mainPage="pratilipi-reader-page">
		<#include "meta/Head.ftl">
		<link rel='import' href='/elements.${lang}/${ mainPage }.html?20160405'>
	</head>
	
	<body>
		<pratilipi-reader-page 
				user-data='{"state":"GUEST","isGuest":true,"isEmailVerified":false}'
				pratilipi='{"pratilipiId":5203435062296576,"title":"துளசி","titleEn":"Thulasi","language":"TAMIL","author":{"name":"வித்யா சுப்ரமணியம்","pageUrl":"/vidya-subramaniam"},"pageUrl":"/vidya-subramaniam/thulasi","coverImageUrl":"http://6.ptlp.co/pratilipi/cover?pratilipiId\u003d5203435062296576\u0026version\u003d1436938921892","readPageUrl":"/read?id\u003d5203435062296576","writePageUrl":"/write?id\u003d5203435062296576","type":"STORY","state":"PUBLISHED","listingDateMillis":1436882745469,"reviewCount":2,"ratingCount":4,"averageRating":4.5,"readCount":463,"fbLikeShareCount":279,"hasAccessToUpdate":false}'
				content='Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et arcu faucibus, gravida diam ut, bibendum urna. Nulla est lorem, porta ullamcorper posuere at, volutpat lacinia libero. Etiam imperdiet enim molestie, vulputate quam non, accumsan nulla. Suspendisse aliquet sagittis leo, at vulputate nibh aliquet sed. Nam molestie quam in risus volutpat molestie. Praesent cursus suscipit rutrum. Aliquam tortor eros, sagittis vitae pellentesque sit amet, lacinia nec mauris. Aliquam mattis sapien vitae quam vulputate, eu consectetur urna tempor. Suspendisse potenti.
Sed at ex ultricies lorem rutrum ultricies vulputate vitae ligula. Vestibulum sit amet ante arcu. Quisque odio lacus, aliquam at consectetur id, eleifend et ipsum. Sed feugiat, leo vel convallis aliquam, turpis elit dictum risus, feugiat tincidunt mi risus in mi. Sed mollis lacinia est sed finibus. Suspendisse nulla arcu, maximus id aliquam eget, venenatis vitae est. Nam sed libero ex.
Vestibulum vel velit non nisi eleifend vulputate in id dui. Donec mollis pellentesque dignissim. Sed porttitor ipsum sed tortor commodo, placerat condimentum neque blandit. Mauris quis ipsum volutpat, elementum tortor et, malesuada ex. Mauris id nisl vitae risus fringilla pharetra. In sollicitudin mattis mauris. Nunc vitae massa pharetra, lacinia velit ut, tristique ante. Praesent eu sem arcu. Aliquam faucibus sed augue at posuere. Donec vitae venenatis eros. Quisque nec mollis est. Sed sagittis turpis at velit imperdiet ornare.
Etiam rhoncus rutrum libero eget fermentum. Cras at porttitor arcu, at viverra mauris. Pellentesque quis pharetra elit, a commodo mauris. Nam ultrices libero in molestie fringilla. Duis vulputate justo quis leo ultricies, sollicitudin porttitor felis luctus. Mauris vitae mattis sapien. Proin aliquet, sem at molestie porta, mauris dolor mollis lacus, in feugiat mauris sapien eu libero.
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis condimentum velit nec orci ornare vehicula. Nunc sapien urna, hendrerit a suscipit in, volutpat sed diam. Sed ut laoreet magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer et metus ut lectus luctus dictum eu non lectus. Ut consequat egestas dolor vitae malesuada. Praesent semper ut lectus eget placerat. Aliquam rutrum accumsan urna at placerat. Suspendisse pretium augue vel dolor vehicula venenatis non eget ante. Mauris elementum enim eu pellentesque sagittis. Sed et tristique nisl. In at risus dui. Donec at mi ornare, vulputate massa ut, cursus dui. Suspendisse nec gravida nisl.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et arcu faucibus, gravida diam ut, bibendum urna. Nulla est lorem, porta ullamcorper posuere at, volutpat lacinia libero. Etiam imperdiet enim molestie, vulputate quam non, accumsan nulla. Suspendisse aliquet sagittis leo, at vulputate nibh aliquet sed. Nam molestie quam in risus volutpat molestie. Praesent cursus suscipit rutrum. Aliquam tortor eros, sagittis vitae pellentesque sit amet, lacinia nec mauris. Aliquam mattis sapien vitae quam vulputate, eu consectetur urna tempor. Suspendisse potenti.
Sed at ex ultricies lorem rutrum ultricies vulputate vitae ligula. Vestibulum sit amet ante arcu. Quisque odio lacus, aliquam at consectetur id, eleifend et ipsum. Sed feugiat, leo vel convallis aliquam, turpis elit dictum risus, feugiat tincidunt mi risus in mi. Sed mollis lacinia est sed finibus. Suspendisse nulla arcu, maximus id aliquam eget, venenatis vitae est. Nam sed libero ex.
Vestibulum vel velit non nisi eleifend vulputate in id dui. Donec mollis pellentesque dignissim. Sed porttitor ipsum sed tortor commodo, placerat condimentum neque blandit. Mauris quis ipsum volutpat, elementum tortor et, malesuada ex. Mauris id nisl vitae risus fringilla pharetra. In sollicitudin mattis mauris. Nunc vitae massa pharetra, lacinia velit ut, tristique ante. Praesent eu sem arcu. Aliquam faucibus sed augue at posuere. Donec vitae venenatis eros. Quisque nec mollis est. Sed sagittis turpis at velit imperdiet ornare.
Etiam rhoncus rutrum libero eget fermentum. Cras at porttitor arcu, at viverra mauris. Pellentesque quis pharetra elit, a commodo mauris. Nam ultrices libero in molestie fringilla. Duis vulputate justo quis leo ultricies, sollicitudin porttitor felis luctus. Mauris vitae mattis sapien. Proin aliquet, sem at molestie porta, mauris dolor mollis lacus, in feugiat mauris sapien eu libero.
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis condimentum velit nec orci ornare vehicula. Nunc sapien urna, hendrerit a suscipit in, volutpat sed diam. Sed ut laoreet magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer et metus ut lectus luctus dictum eu non lectus. Ut consequat egestas dolor vitae malesuada. Praesent semper ut lectus eget placerat. Aliquam rutrum accumsan urna at placerat. Suspendisse pretium augue vel dolor vehicula venenatis non eget ante. Mauris elementum enim eu pellentesque sagittis. Sed et tristique nisl. In at risus dui. Donec at mi ornare, vulputate massa ut, cursus dui. Suspendisse nec gravida nisl.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et arcu faucibus, gravida diam ut, bibendum urna. Nulla est lorem, porta ullamcorper posuere at, volutpat lacinia libero. Etiam imperdiet enim molestie, vulputate quam non, accumsan nulla. Suspendisse aliquet sagittis leo, at vulputate nibh aliquet sed. Nam molestie quam in risus volutpat molestie. Praesent cursus suscipit rutrum. Aliquam tortor eros, sagittis vitae pellentesque sit amet, lacinia nec mauris. Aliquam mattis sapien vitae quam vulputate, eu consectetur urna tempor. Suspendisse potenti.
Sed at ex ultricies lorem rutrum ultricies vulputate vitae ligula. Vestibulum sit amet ante arcu. Quisque odio lacus, aliquam at consectetur id, eleifend et ipsum. Sed feugiat, leo vel convallis aliquam, turpis elit dictum risus, feugiat tincidunt mi risus in mi. Sed mollis lacinia est sed finibus. Suspendisse nulla arcu, maximus id aliquam eget, venenatis vitae est. Nam sed libero ex.
Vestibulum vel velit non nisi eleifend vulputate in id dui. Donec mollis pellentesque dignissim. Sed porttitor ipsum sed tortor commodo, placerat condimentum neque blandit. Mauris quis ipsum volutpat, elementum tortor et, malesuada ex. Mauris id nisl vitae risus fringilla pharetra. In sollicitudin mattis mauris. Nunc vitae massa pharetra, lacinia velit ut, tristique ante. Praesent eu sem arcu. Aliquam faucibus sed augue at posuere. Donec vitae venenatis eros. Quisque nec mollis est. Sed sagittis turpis at velit imperdiet ornare.
Etiam rhoncus rutrum libero eget fermentum. Cras at porttitor arcu, at viverra mauris. Pellentesque quis pharetra elit, a commodo mauris. Nam ultrices libero in molestie fringilla. Duis vulputate justo quis leo ultricies, sollicitudin porttitor felis luctus. Mauris vitae mattis sapien. Proin aliquet, sem at molestie porta, mauris dolor mollis lacus, in feugiat mauris sapien eu libero.
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis condimentum velit nec orci ornare vehicula. Nunc sapien urna, hendrerit a suscipit in, volutpat sed diam. Sed ut laoreet magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer et metus ut lectus luctus dictum eu non lectus. Ut consequat egestas dolor vitae malesuada. Praesent semper ut lectus eget placerat. Aliquam rutrum accumsan urna at placerat. Suspendisse pretium augue vel dolor vehicula venenatis non eget ante. Mauris elementum enim eu pellentesque sagittis. Sed et tristique nisl. In at risus dui. Donec at mi ornare, vulputate massa ut, cursus dui. Suspendisse nec gravida nisl.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In et arcu faucibus, gravida diam ut, bibendum urna. Nulla est lorem, porta ullamcorper posuere at, volutpat lacinia libero. Etiam imperdiet enim molestie, vulputate quam non, accumsan nulla. Suspendisse aliquet sagittis leo, at vulputate nibh aliquet sed. Nam molestie quam in risus volutpat molestie. Praesent cursus suscipit rutrum. Aliquam tortor eros, sagittis vitae pellentesque sit amet, lacinia nec mauris. Aliquam mattis sapien vitae quam vulputate, eu consectetur urna tempor. Suspendisse potenti.
Sed at ex ultricies lorem rutrum ultricies vulputate vitae ligula. Vestibulum sit amet ante arcu. Quisque odio lacus, aliquam at consectetur id, eleifend et ipsum. Sed feugiat, leo vel convallis aliquam, turpis elit dictum risus, feugiat tincidunt mi risus in mi. Sed mollis lacinia est sed finibus. Suspendisse nulla arcu, maximus id aliquam eget, venenatis vitae est. Nam sed libero ex.
Vestibulum vel velit non nisi eleifend vulputate in id dui. Donec mollis pellentesque dignissim. Sed porttitor ipsum sed tortor commodo, placerat condimentum neque blandit. Mauris quis ipsum volutpat, elementum tortor et, malesuada ex. Mauris id nisl vitae risus fringilla pharetra. In sollicitudin mattis mauris. Nunc vitae massa pharetra, lacinia velit ut, tristique ante. Praesent eu sem arcu. Aliquam faucibus sed augue at posuere. Donec vitae venenatis eros. Quisque nec mollis est. Sed sagittis turpis at velit imperdiet ornare.
Etiam rhoncus rutrum libero eget fermentum. Cras at porttitor arcu, at viverra mauris. Pellentesque quis pharetra elit, a commodo mauris. Nam ultrices libero in molestie fringilla. Duis vulputate justo quis leo ultricies, sollicitudin porttitor felis luctus. Mauris vitae mattis sapien. Proin aliquet, sem at molestie porta, mauris dolor mollis lacus, in feugiat mauris sapien eu libero.
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis condimentum velit nec orci ornare vehicula. Nunc sapien urna, hendrerit a suscipit in, volutpat sed diam. Sed ut laoreet magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer et metus ut lectus luctus dictum eu non lectus. Ut consequat egestas dolor vitae malesuada. Praesent semper ut lectus eget placerat. Aliquam rutrum accumsan urna at placerat. Suspendisse pretium augue vel dolor vehicula venenatis non eget ante. Mauris elementum enim eu pellentesque sagittis. Sed et tristique nisl. In at risus dui. Donec at mi ornare, vulputate massa ut, cursus dui. Suspendisse nec gravida nisl.'
				></pratilipi-pratilipi-page>
	</body>
	
</html>
