package com.pratilipi.common.type;

public enum MailingList {
	
	LAUNCH_ANNOUNCEMENT_ANDROID_APP,
	
	LAUNCH_ANNOUNCEMENT_URDU,
	LAUNCH_ANNOUNCEMENT_ODIA,
	LAUNCH_ANNOUNCEMENT_PUNJABI,
	LAUNCH_ANNOUNCEMENT_ASSAMESE,
	LAUNCH_ANNOUNCEMENT_MAITHILI,
	LAUNCH_ANNOUNCEMENT_BHOJPURI,
	LAUNCH_ANNOUNCEMENT_OTHER,
	
}
